export const brandOptions: string[] = ['AC', 'Acura', 'Adler', 'Alfa Romeo', 'Alpina', 'Alpine', 'AM General', 'AMC', 'Ariel', 'Aro', 'Asia', 'Aston Martin', 'Audi', 'Aurus', 'Austin', 'Austin Healey', 'Autobianchi', 'BAIC', 'Bajaj', 'Baltijas Dzips', 'Batmobile', 'Bentley', 'Bertone', 'Bilenkin', 'Bitter', 'BMW', 'Borgward', 'Brabus', 'Brilliance', 'Bristol', 'Bufori', 'Bugatti', 'Buick', 'BYD', 'Byvin', 'Cadillac', 'Callaway', 'Carbodies', 'Caterham', 'Chana', 'Changan', 'ChangFeng', 'Changhe', 'Chery', 'Chevrolet', 'Chrysler', 'Citroen', 'Cizeta', 'Coggiola', 'Cord', 'Dacia', 'Dadi', 'Daewoo', 'Daihatsu', 'Daimler', 'Datsun', 'De Tomaso', 'Delage', 'DeLorean', 'Derways', 'DeSoto', 'Dodge', 'DongFeng', 'Doninvest', 'Donkervoort', 'DS', 'DW Hower', 'E-Car', 'Eagle', 'Eagle Cars', 'Excalibur', 'FAW', 'Ferrari', 'Fiat', 'Fisker', 'Flanker', 'Ford', 'Foton', 'FSO', 'Fuqi', 'GAC', 'Geely', 'Genesis', 'Geo', 'GMC', 'Gonow', 'Gordon', 'GP', 'Great Wall', 'Hafei', 'Haima', 'Hanomag', 'Haval', 'Hawtai', 'Hindustan', 'Hispano-Suiza', 'Holden', 'Honda', 'Horch', 'Huanghai', 'Hudson', 'Hummer', 'Hyundai', 'Infiniti', 'Innocenti', 'Invicta', 'Iran Khodro', 'Isdera', 'Isuzu', 'Jac', 'Jaguar', 'Jeep', 'Jensen', 'Jinbei', 'JMC', 'Kia', 'Koenigsegg', 'KTM AG', 'LADA (ВАЗ)', 'Lamborghini', 'Lancia', 'Land Rover', 'Landwind', 'Lexus', 'Liebao Motor', 'Lifan', 'Ligier', 'Lincoln', 'Lotus', 'LTI', 'Lucid', 'Luxgen', 'Mahindra', 'Marcos', 'Marlin', 'Marussia', 'Maruti', 'Maserati', 'Maybach', 'Mazda', 'McLaren', 'Mega', 'Mercedes-Benz', 'Mercury', 'Metrocab', 'MG', 'Microcar', 'Minelli', 'Mini', 'Mitsubishi', 'Mitsuoka', 'Morgan', 'Morris', 'Nash', 'Nissan', 'Noble', 'Oldsmobile', 'Opel', 'Osca', 'Packard', 'Pagani', 'Panoz', 'Perodua', 'Peugeot', 'PGO', 'Piaggio', 'Plymouth', 'Pontiac', 'Porsche', 'Premier', 'Proton', 'PUCH', 'Puma', 'Qoros', 'Qvale', 'Rambler', 'Ravon', 'Reliant', 'Renaissance', 'Renault', 'Renault Samsung', 'Rezvani', 'Rimac', 'Rolls-Royce', 'Ronart', 'Rover', 'Saab', 'Saipa', 'Saleen', 'Santana', 'Saturn', 'Scion', 'Seat', 'Shanghai Maple', 'ShuangHuan', 'Simca', 'Skoda', 'Smart', 'Soueast', 'Spectre', 'Spyker', 'SsangYong', 'Steyr', 'Studebaker', 'Subaru', 'Suzuki', 'Talbot', 'TATA', 'Tatra', 'Tazzari', 'Tesla', 'Think', 'Tianma', 'Tianye', 'Tofas', 'Toyota', 'Trabant', 'Tramontana', 'Triumph', 'TVR', 'Ultima', 'Vauxhall', 'Vector', 'Venturi', 'Volkswagen', 'Volvo', 'Vortex', 'W Motors', 'Wanderer', 'Wartburg', 'Westfield', 'Wiesmann', 'Willys', 'Xin Kai', 'Zastava', 'Zenos', 'Zenvo', 'Zibar', 'Zotye', 'ZX', 'Автокам', 'ГАЗ', 'Ё-мобиль', 'ЗАЗ', 'ЗИЛ', 'ЗиС', 'ИЖ', 'Канонир', 'Комбат', 'ЛуАЗ', 'Москвич', 'СМЗ', 'ТагАЗ', 'УАЗ'];
export const amountDoors: string[] = ['1', '2', '3', '4', '5'];
export const bodyType: string[] = ['Внедорожник',
  'Кабриолет', 'Комби', 'Купе', 'Минивэн',
  'Пикап' , 'Родстэр', 'Седан', 'Универсал',
  'Хэтчбек', 'Лимузин', 'Спорт-купе', 'Лифтбек' ];
export const driveType: string[] = ['Передний', 'Задний', 'Полный'];
export const transmission: string[] = ['Механика', 'Автомат', 'Полуавтомат'];
export const engineType: string[] = ['Бензин', 'Дизель', 'Газ/Бензин', 'Гибрид', 'Электро'];
export const condition: string[] = ['Отличное', 'Хорошее', 'Удовлетворительное', 'Битый', 'Новый'];
